language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
script:
    - npm test
   
services:
    - postgresql
before_script:
    - psql -c "CREATE DATABASE teamwork;" -U postgres